import type { Component } from "vue";
import {
  Aim,
  Avatar,
  Box,
  CircleCheck,
  CircleClose,
  Clock,
  Coin,
  Collection,
  Connection,
  DataAnalysis,
  DataBoard,
  Document,
  Download,
  Edit,
  Flag,
  FolderOpened,
  Goods,
  Grid,
  HomeFilled,
  House,
  Key,
  List,
  Lock,
  Menu,
  Message,
  Monitor,
  Notebook,
  PieChart,
  Postcard,
  PriceTag,
  Refresh,
  Setting,
  Share,
  Shop,
  Tickets,
  Tools,
  TrendCharts,
  Upload,
  User,
  UserFilled,
  View,
  Wallet,
  Warning,
} from "@element-plus/icons-vue";

/** 侧栏图标键（一级模块 / 二级子页） */
export type NavIconKey = string;

const ICONS: Record<NavIconKey, Component> = {
  dashboard: HomeFilled,
  key: Key,
  monitor: Monitor,
  billing: Wallet,
  supplier: Shop,
  model: Box,
  customer: User,
  doc: Document,
  report: DataAnalysis,
  users: User,
  access: Lock,
  system: Setting,
  menu: Menu,
  list: List,
  audit: View,
  profile: Avatar,
  integration: Connection,
  probe: Aim,
  "key-rotation": Refresh,
  master: Collection,
  lines: Share,
  pricing: PriceTag,
  tenants: House,
  org: Grid,
  contract: Tickets,
  invoice: Tickets,
  credit: Coin,
  editor: Edit,
  publish: Upload,
  visibility: View,
  preset: DataBoard,
  olap: DataAnalysis,
  export: Download,
  subscribe: Message,
  "audit-queue": Clock,
  whitelist: CircleCheck,
  blacklist: CircleClose,
  kyc: Postcard,
  admins: Avatar,
  roles: UserFilled,
  menus: Menu,
  "audit-log": Notebook,
  sensitive: Warning,
  "export-approval": FolderOpened,
  flags: Flag,
  global: Tools,
  usage: TrendCharts,
  quota: PieChart,
  sku: Goods,
  adjust: Edit,
};

/** 一级模块 pathBase → 图标 */
export const MODULE_ICON_BY_PATH: Record<string, NavIconKey> = {
  keys: "key",
  suppliers: "supplier",
  models: "model",
  customers: "customer",
  docs: "doc",
  reports: "report",
  users: "users",
  access: "access",
  system: "system",
  billing: "billing",
};

/** 二级子页 id → 图标（各模块共用 id 如 list / audit） */
export function leafIconKey(pageId: string): NavIconKey {
  return ICONS[pageId] ? pageId : "doc";
}

export function resolveNavIconComponent(iconKey: NavIconKey): Component {
  return ICONS[iconKey] ?? Document;
}
