/** output/README.md 内容生成 */

import {
  TEXT_SHEET_ORDER,
  TEXT_PRICING_XLSX,
  IMAGE_PRICING_XLSX,
  VIDEO_PRICING_XLSX,
} from "./paths.mjs";
import path from "node:path";

export function renderOutputReadme({ generatedAt, modelCount, scrapedAt, aigcDate }) {
  const base = path.basename;
  return [
    "# Trinity 价目导出索引",
    "",
    `> 更新 ${generatedAt} · 生文模型 **${modelCount}** 款`,
    `> TokenHub/百炼：${scrapedAt} · AIGC 价目表：${aigcDate}`,
    "",
    "## 对外 Excel（按模态分册）",
    "",
    "| 文件 | 模态 | 说明 |",
    "|------|------|------|",
    `| [${base(TEXT_PRICING_XLSX)}](./${base(TEXT_PRICING_XLSX)}) | 生文 | 刊例校验 · **汇总-供应商vs官方**（第 2 Sheet）· 各供应商分表 |`,
    `| [${base(IMAGE_PRICING_XLSX)}](./${base(IMAGE_PRICING_XLSX)}) | 生图 | 官方价对比 |`,
    `| [${base(VIDEO_PRICING_XLSX)}](./${base(VIDEO_PRICING_XLSX)}) | 生视频 | 官方价对比 |`,
    "",
    "生文册 Sheet：",
    "",
    TEXT_SHEET_ORDER.map((s) => `- ${s}`).join("\n"),
    "",
    "## 目录结构",
    "",
    "```",
    "output/",
    "├── README.md",
    "├── trinity-pricing-text.xlsx",
    "├── trinity-pricing-image.xlsx",
    "├── trinity-pricing-video.xlsx",
    "├── online/",
    "├── upstream/",
    "├── official/",
    "├── openrouter/",
    "├── draft/",
    "└── validate/",
    "```",
    "",
    "## 常用文件（非 Excel）",
    "",
    "| 路径 | 命令 | 说明 |",
    "|------|------|------|",
    "| [online/prices-api.json](./online/prices-api.json) | `pricing:fetch` | 平台线上刊例真源 |",
    "| [upstream/summary.md](./upstream/summary.md) | `pricing:upstream` | 生文刊例对比（与 Excel 同源） |",
    "| [official/text.json](./official/text.json) | `pricing:upstream` | 同上 · JSON（与 Excel 同步） |",
    "| [official/text.md](./official/text.md) | `pricing:upstream` | 同上 · Markdown |",
    "| [official/image.md](./official/image.md) | `pricing:compare:official -- --modality=image` | 生图官方价 |",
    "| [official/video.md](./official/video.md) | `pricing:compare:official -- --modality=video` | 生视频官方价 |",
    "| [openrouter/text.md](./openrouter/text.md) | `pricing:compare:openrouter` | 官网 vs OpenRouter |",
    "| [draft/0.65_prices-api.json](./draft/0.65_prices-api.json) | `pricing:gen-65` | 建议刊例草案 |",
    "",
    "供应商 JSON 真源见 `pricing/suppliers/SOURCES.md`。",
    "",
  ].join("\n");
}
